image: mcr.microsoft.com/dotnet/sdk:6.0
pipelines:
  tags:
   "v-*.*.*":
    - step:
        caches:
          - dotnetcore
        script: 
          - export VERSION_NUMBER=${BITBUCKET_TAG/v-/}
          - apt-get update -y
          - apt-get install -y xmlstarlet
          - xmlstarlet ed --inplace -u "//Project//PropertyGroup/Version" -v $VERSION_NUMBER $SOLUTION_NAME.csproj
          - dotnet restore $SOLUTION_NAME.sln
          - dotnet build --no-restore $SOLUTION_NAME.sln --configuration $CONFIGURATION
          - dotnet nuget push -s https://ba-nuget.primitive.io/ -k $API_KEY bin/$CONFIGURATION/$SOLUTION_NAME.$VERSION_NUMBER.nupkg
    - step:
        name: Publish to NPM
        image: node:12.20.2
        script:
          - export VERSION=${BITBUCKET_TAG/v-/}
          - npm version $VERSION --force
          - pipe: atlassian/npm-publish:0.2.0
            variables:
              NPM_TOKEN: $NPM_TOKEN

 