image: mcr.microsoft.com/dotnet/sdk:6.0
pipelines:
  tags:
   "v-*.*.*":
    - step:
        caches:
          - dotnetcore
        script: 
          - export VERSION_NUMBER=${BITBUCKET_TAG/v-/}
          - apt-get update -y
          - apt-get install -y xmlstarlet
          - xmlstarlet ed --inplace -u "//Project//PropertyGroup/Version" -v $VERSION_NUMBER $SOLUTION_NAME.csproj
          - dotnet restore $SOLUTION_NAME.sln
          - dotnet build --no-restore $SOLUTION_NAME.sln --configuration $CONFIGURATION
          - dotnet nuget push -s $SERVER_URL -k $API_KEY bin/$CONFIGURATION/$SOLUTION_NAME.$VERSION_NUMBER.nupkg

 